get http://localhost:3000/api/geotags

###

post http://localhost:3000/api/geotags
Content-Type: application/json

{
    "latitude": 48.2,
    "longitude": 11.6,
    "name": "München"
}

###

get http://localhost:3000/api/geotags/12

###

delete http://localhost:3000/api/geotags/200

###

put http://localhost:3000/api/geotags/0
Content-Type: application/json

{
    "latitude": 48.2,
    "longitude": 11.6,
    "name": "Castle Update"
}